USE CASE1; 
SELECT * FROM WEEKLY_SALES LIMIT 10; 	

CREATE TABLE CLEAN_WEEKLY_SALES AS 
SELECT WEEK_DATE, WEEK(WEEK_DATE) AS WEEK_NUM, MONTH(WEEK_DATE) AS MONTH_NUM,
YEAR(WEEK_DATE) AS CALENDAR_YEAR, REGION, PLATFORM, 
CASE 
WHEN SEGMENT = NULL THEN 'UNKNOW' 
ELSE SEGMENT 
END AS SEGMENT,
CASE 
WHEN RIGHT(SEGMENT,1) ='1' THEN 'YOUNG ADULTS' 
WHEN RIGHT(SEGMENT,1) ='2' THEN 'MIDDLE AGE'
WHEN RIGHT(SEGMENT,1) IN('3','4') THEN 'RETIREES'
ELSE 'UNKNOW'
END AS AGE_BAND,
CASE 
WHEN LEFT(SEGMENT,1) ='C' THEN 'COUPLES'
WHEN LEFT(SEGMENT,1) = 'F' THEN 'FAMILIES'
ELSE 'UNKNOW' 
END AS DEMOGRAPHIC, CUSTOMER_TYPE,TRANSACTIONS,SALES,
ROUND(SALES/TRANSACTIONS,2) AS 'AVG_TRANSACTIONS'
FROM WEEKLY_SALES; 

SELECT * FROM CLEAN_WEEKLY_SALES LIMIT 10; 
## DATA EXPLORATION 
##  Q-1 SOLUTION 
CREATE TABLE SEQ100(X INT auto_increment PRIMARY KEY); 
insert into seq100 values (),(),(),(),(),(),(),(),(),();
insert into seq100 values (),(),(),(),(),(),(),(),(),();
insert into seq100 values (),(),(),(),(),(),(),(),(),();
insert into seq100 values (),(),(),(),(),(),(),(),(),();
insert into seq100 values (),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100  SELECT X+50 FROM SEQ100; 
SELECT * FROM SEQ100; 
CREATE TABLE SEQ52 AS(SELECT X FROM SEQ100 LIMIT 52);
SELECT * FROM SEQ52; 
SELECT DISTINCT X AS WEEK_DAY FROM SEQ52
WHERE X NOT IN(SELECT DISTINCT WEEK_NUM FROM CLEAN_WEEKLY_SALES); 

# Q-2 

SELECT CALENDAR_YEAR, SUM(TRANSACTIONS) AS TOTAL_TRANSACTIONS 
FROM CLEAN_WEEKLY_SALES 
GROUP BY CALENDAR_YEAR;

# Q-3 
SELECT REGION, MONTH_NUM,SUM(SALES) AS TOTAL_SALES  
FROM CLEAN_WEEKLY_SALES 
GROUP BY MONTH_NUM,REGION; 

# Q-4 
SELECT PLATFORM,SUM(TRANSACTIONS)AS COUNT_TRAN 
FROM CLEAN_WEEKLY_SALES 
GROUP BY PLATFORM; 

# Q-5  

WITH CTE_MONTHLY_PLATFROM_SALES AS 
(SELECT MONTH_NUM,CALENDAR_YEAR,PLATFORM,SUM(SALES) AS MONTHLY_SALES 
FROM CLEAN_WEEKLY_SALES 
GROUP BY MONTH_NUM,CALENDAR_YEAR,PLATFORM) 
SELECT MONTH_NUM,CALENDAR_YEAR, 
ROUND(100*MAX(CASE WHEN PLATFORM ='RETAIL'
THEN MONTHLY_SALES ELSE NULL END)/SUM(MONTHLY_SALES),2) AS RETAIL_PERCENTAGE,
ROUND(100*MAX(CASE WHEN PLATFORM ='SHOPIFY' 
THEN MONTHLY_SALES ELSE NULL END)/SUM(MONTHLY_SALES),2) AS SHOPIGY_PERCENATGE 
FROM CTE_MONTHLY_PLATFROM_SALES 
GROUP BY MONTH_NUM,CALENDAR_YEAR; 

## Q-6  

SELECT DEMOGRAPHIC, CALENDAR_YEAR, SUM(SALES) AS YEARLY_SALES, 
ROUND(100*SUM(SALES)/SUM(SUM(SALES)) OVER (PARTITION BY DEMOGRAPHIC ),2) AS PERCENTAGE 
FROM CLEAN_WEEKLY_SALES 
GROUP BY DEMOGRAPHIC,CALENDAR_YEAR; 

# Q-7 
SELECT AGE_BAND, DEMOGRAPHIC,SUM(SALES) AS TOTAL_SALES
FROM CLEAN_WEEKLY_SALES 
WHERE PLATFORM ='RETAIL'
GROUP BY AGE_BAND, DEMOGRAPHIC
ORDER BY TOTAL_SALES DESC; 

SELECT SALES,  PLATFORM  
FROM CLEAN_WEEKLY_SALES 






